version: "3.7"

services:
#Mongo db service
    mongo_db:
        image: mongo
        volumes:
            - data:/data/db
        ports:
            - "27017:27017"
        networks:
            - book_network
#Backend for Node js
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./src:/app/src
            - /app/node_modules
        restart: always
        ports:
            - "5000:5000"
        depends_on:
            - mongo_db
        environment:
          ME_CONFIG_MONGODB_ADMINUSERNAME: root
          ME_CONFIG_MONGODB_ADMINPASSWORD: example
        networks:
            - book_network
#Front-end client for React js
    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        volumes:
            - ./client/src:/app/src
            - /app/node_modules
        depends_on:
            - backend
        ports:
            - "3000:3000"
        environment:
            - CHOKIDAR_USEPOLLING=true
        stdin_open: true
        tty: true
        networks:
            - book_network
#Network
networks:
    book_network:
        driver: bridge
#Volumes
volumes:
    data:
    backend_data:
    node_modules:
    web-root:
        driver: local